version: '3.1'

services:
  api:
    container_name: workout-tracker-api
    image: workout-tracker-api-image
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: workout-tracker-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: workout-tracker-user
      POSTGRES_PASSWORD: workout-tracker-password
      POSTGRES_DB: workout-tracker-db
    volumes:
       - postgres-db:/data/postgres

volumes:
  postgres-db:
    driver: local